services:
  - type: web
    name: convention-iframe
    env: node
    plan: starter
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npm run migrate deploy && npm run start
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.14.2
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: stt-pg
          property: connectionString

databases:
  - name: stt-pg
    plan: starter